# Generated by Django 4.2.7 on 2023-11-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_is_zyarat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_zyarat',
        ),
    ]
