# Generated by Django 4.2.7 on 2023-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_is_zyarat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='is_zyarat',
            field=models.BooleanField(default=True),
        ),
    ]
