# Generated by Django 4.2.7 on 2023-11-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_content_slug_alter_mainpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.content'),
        ),
    ]
