# Generated by Django 4.2.7 on 2023-11-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_content_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='is_amal',
            field=models.BooleanField(default=False),
        ),
    ]
