# Generated by Django 4.2.7 on 2023-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mainpost_is_amal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='is_amal',
        ),
        migrations.AddField(
            model_name='mainpost',
            name='is_not_amal',
            field=models.BooleanField(default=True),
        ),
    ]
