# Generated by Django 4.2.7 on 2024-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_mainpost_is_amal_mainpost_is_not_amal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
